### ISSUE TITLE
GUI not grabing max_movment_speed from config

### ISSUE THREAD

**Issue by tedztar** [tedztar/Portable_Spider_Cam#4]
**Describe the bug**
The GUI is not grabbing the correct max_movment_speed from config. It looks like it is grabbing the variable before the config file is read, making it grab the incorrect value.

**Comment by tedztar** [comment]
In CINGIF.py
![image](https://user-images.githubusercontent.com/17801794/50607826-9c344580-0e98-11e9-8eef-a806d5c9837f.png)

**Comment by SmartyJem** [comment]
Yes that change now should set max_movement_speed, now if you get the GUI to recover the information from CONFIG you should now get the value that gets read from CONFIG inside the .config file.
